# Changes the title color of the sidebar playtime scoreboard
## Valid colors are:
##  BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE
playtimeTitleColor: "AQUA"

# Enables a health display below a player's name
enableHealth: true

# Enables an update check for this plugin. If it there is an update, it will be disabled. (Except for Patches, enable failOnPatch for that)
enableUpdateCheck: true
failOnPatch: false
