name: VanillaUtility
version: 1.4.2
main: com.github.shioku.vanillautility.VanillaUtility
api-version: '1.21'
website: 'https://github.com/Shioku1337/VanillaUtility/releases'

commands:
  chunkloader:
    aliases: [cl]
    description: "Load and unload the chunk you're standing in."
    permission: "vu.chunkloader"
    usage: "/<label> add,remove [all,(x,z)]"
  advancementlist:
    aliases: [advl]
    description: "List specific advancements to show the progress you've made and what is missing."
    permission: "vu.advancementlist"
    usage: "/<label> (advancement_key)"
